# -*- coding: utf-8 -*-
"""Lab-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O-k1jRQU7tRXIRn-9ghKLiuJNQ50ejAk
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

df = pd.read_csv("company_sales_data.csv")
print(df.head())

# 1. Read Total profit of all months and show it using a line plot Total profit data provided for each month. Generated line plot must include the
# following properties: –
# • X label name = Month Number
# • Y label name = Total profit

plt.plot(
    df["month_number"],
    df["total_profit"]
)

plt.xlabel("Month Number")
plt.ylabel("Total Profit")

plt.show()

# 2. Get total profit of all months and show line plot with the following Style
# properties
# Generated line plot must include following Style properties: –
# • Line Style dotted and Line-color should be red
# • Show legend at the lower right location.
# • X label name = Month Number
# • Y label name = Sold units number
# • Add a circle marker.
# • Line marker color as read
# • Line width should be 3


plt.plot(
    df["month_number"],
    df["total_profit"],
    linestyle=":",
    color="red",
    marker="o",
    markerfacecolor="red",
    linewidth=3,
    label="total_profit"
)

plt.xlabel("Month Number")
plt.ylabel("Total Profit")

plt.legend(loc="lower right")

plt.show()

# 3. Read all product sales data and show it using a multiline plot
# Display the number of units sold per month for each product using multiline
# plots. (i.e., Separate Plotline for each product ).

plt.plot(
    df["month_number"],
    df["facecream"],
    label="Face Cream"
)

plt.plot(
    df["month_number"],
    df["facewash"],
    label="Face Wash"
)

plt.plot(
    df["month_number"],
    df["toothpaste"],
    label="toothpaste"
)

plt.plot(
    df["month_number"],
    df["bathingsoap"],
    label="Bathing Soap"
)

plt.plot(
    df["month_number"],
    df["shampoo"],
    label="Shampoo"
)

plt.plot(
    df["month_number"],
    df["moisturizer"],
    label="Moisturizer"
)

plt.xlabel("Month Number")
plt.ylabel("Units Sold")

plt.legend()

plt.show()

# 4. Read toothpaste sales data of each month and show it using a scatter plot
# Also, add a grid in the plot. gridline style should “–“.

plt.scatter(
    df["month_number"],
    df["toothpaste"]
)

plt.xlabel("Month Number")
plt.ylabel("ToothPaste Sales")

plt.grid(
    True,
    linestyle="-"
)

plt.show()

# 5. Read face cream and facewash product sales data and show it using the
# bar chart
# The bar chart should display the number of units sold per month for each
# product. Add a separate bar for each product in the same chart.

x = np.arange(len(df["month_number"]))

width = 0.4

plt.bar(
    x - width/2,
    df["facecream"],
    width=width,
    label="Face Cream"
)

plt.bar(
    x + width/2,
    df["facewash"],
    width=width,
    label="facewash"
)

plt.xticks(
    x,
    df["month_number"]
)

plt.xlabel("Month Number")
plt.ylabel("Units Sold")

plt.legend()

plt.show()

# 6. Read sales data of bathing soap of all months and show it using a bar
# chart. Save this plot to your hard disk

plt.bar(
    df["month_number"],
    df["bathingsoap"]
)

plt.xlabel("Month Number")
plt.ylabel("Bathing Soap Sales")

plt.savefig("bathing_soap_sales.png")

plt.show()

# 7. Read the total profit of each month and show it using the histogram to see
# the most common profit ranges

plt.hist(
    df["total_profit"],
    bins=10
)

plt.xlabel("Total Profit")
plt.ylabel("Frequency")

plt.show()

# 8. Calculate total sale data for last year for each product and show it using a
# Pie chart
# Note: In Pie chart display Number of units sold per year for each product in
# percentage.

products = [
    "Face Cream",
    "Face Wash",
    "ToothPaste",
    "Bathing soap",
    "Shampoo",
    "Moisturizer"
]

sales = [
    df["facecream"].sum(),
    df["facewash"].sum(),
    df["toothpaste"].sum(),
    df["bathingsoap"].sum(),
    df["shampoo"].sum(),
    df["moisturizer"].sum()
]

plt.pie(
    sales,
    labels=products,
    autopct="%1.1f%%"
)

plt.title("Total Sales for Last Year")

plt.show()

# 9. Read Bathing soap facewash of all months and display it using the Subplot

plt.subplot(2, 1, 1)

plt.plot(
    df["month_number"],
    df["bathingsoap"]
)

plt.title("Bathing Soap Sales")

plt.subplot(2, 1, 2)

plt.plot(
    df["month_number"],
    df["facewash"]
)

plt.title("Face Wash Sales")

plt.tight_layout()

plt.show()

# 10.Read all product sales data and show it using the stack plot

plt.stackplot(
    df["month_number"],
    df["facecream"],
    df["facewash"],
    df["toothpaste"],
    df["bathingsoap"],
    df["shampoo"],
    df["moisturizer"],
    labels=[
        "Face Cream",
        "Face Wash",
        "ToothPaste",
        "Bathing Soap",
        "Shampoo",
        "Moisturizer"
    ]
)

plt.xlabel("Month Number")
plt.ylabel("Units Sold")

plt.legend(loc="upper left")

plt.show()